[options]
; Database
db_host = host.docker.internal
db_port = 5432
db_user = odoo
db_password = odoo
db_name = hrm_pro_18

; Addons
addons_path = /opt/odoo/source/odoo/addons,/opt/odoo/custom,/opt/odoo/hrm_addons,/opt/odoo/third_party_addons,/opt/odoo/core_addons,/opt/odoo/odoo/addons,/opt/odoo/queue

; Server
http_port = 8069
proxy_mode = False
without_demo = all

; Dev
dev_mode = xml

; Data dir
data_dir = /opt/odoo/data

; Logging
log_level = info
