#!/usr/bin/env bash
# wt-up.sh — Create a git worktree + dedicated Docker container for an agent task.
#
# Usage:
#   ./scripts/wt-up.sh <branch-name> [port]
#
# Examples:
#   ./scripts/wt-up.sh fix/connector-stat-buttons 8071
#   ./scripts/wt-up.sh feat/loop-node             8072
#
# What it does:
#   1. Creates git worktree at ../worktrees/wt-<slug>/
#   2. Clones the base DB into wt_<slug>
#   3. Writes a per-worktree .env.wt (gitignored)
#   4. Starts a dedicated Docker Compose container on the given port
#
# After running, the agent works exclusively in the worktree directory.
# The main repo (port 8069) is never touched.

set -euo pipefail

REPO_ROOT="$(git -C "$(dirname "$0")/.." rev-parse --show-toplevel)"
SCRIPTS_DIR="${REPO_ROOT}/scripts"

BRANCH="${1:?Usage: wt-up.sh <branch-name> [port]}"
PORT="${2:-}"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

slug_from_branch() {
    # lowercase, replace / and _ and spaces with -, strip special chars, max 28 chars
    echo "$1" | tr '[:upper:]' '[:lower:]' | sed 's|[/_. ]|-|g' | sed 's|[^a-z0-9-]||g' | cut -c1-28
}

next_free_port() {
    local p=8071
    while nc -z 127.0.0.1 "$p" 2>/dev/null; do
        p=$((p + 1))
        [ $p -gt 8099 ] && { echo "ERROR: No free port in range 8071-8099" >&2; exit 1; }
    done
    echo "$p"
}

# ---------------------------------------------------------------------------
# Derive names
# ---------------------------------------------------------------------------

SLUG="$(slug_from_branch "$BRANCH")"
[ -z "$PORT" ] && PORT="$(next_free_port)"

DB_NAME="wt_${SLUG}"
WT_PATH="${REPO_ROOT}/../worktrees/wt-${SLUG}"
PROJECT_NAME="wt-${SLUG}"
CONTAINER_NAME="odoo-wt-${SLUG}"
REGISTRY_FILE="${REPO_ROOT}/.wt-registry"

echo ""
echo "=== wt-up: ${BRANCH} ==="
echo "  slug:      ${SLUG}"
echo "  port:      ${PORT}"
echo "  db:        ${DB_NAME}"
echo "  path:      ${WT_PATH}"
echo "  container: ${CONTAINER_NAME}"
echo ""

# ---------------------------------------------------------------------------
# 1. Git worktree
# ---------------------------------------------------------------------------

if [ -d "$WT_PATH" ]; then
    echo "[wt-up] Worktree already exists — skipping git worktree add"
else
    mkdir -p "$(dirname "$WT_PATH")"
    # Branch may already exist (re-running after partial setup)
    if git -C "$REPO_ROOT" branch --list "$BRANCH" | grep -q .; then
        git -C "$REPO_ROOT" worktree add "$WT_PATH" "$BRANCH"
    else
        git -C "$REPO_ROOT" worktree add "$WT_PATH" -b "$BRANCH"
    fi
    echo "[wt-up] Worktree created: ${WT_PATH}"
fi

# ---------------------------------------------------------------------------
# 2. Clone DB from base (skip if already exists)
# ---------------------------------------------------------------------------

# Source main .env for DB credentials
# shellcheck source=/dev/null
source "${REPO_ROOT}/docker/.env"
DB_HOST_VAL="${DB_HOST:-192.168.100.124}"
DB_PORT_VAL="${DB_PORT:-5432}"
DB_USER_VAL="${DB_USER:-odoo}"
DB_PASS_VAL="${DB_PASSWORD:-odoo}"

PGPASSWORD="$DB_PASS_VAL" psql -h "$DB_HOST_VAL" -p "$DB_PORT_VAL" -U "$DB_USER_VAL" -d postgres \
    -tc "SELECT 1 FROM pg_database WHERE datname = '${DB_NAME}'" \
    | grep -q 1 && DB_EXISTS=1 || DB_EXISTS=0

if [ "$DB_EXISTS" -eq 1 ]; then
    echo "[wt-up] DB already exists — skipping clone: ${DB_NAME}"
else
    BASE_DB="${PGDATABASE:-hrm_pro_18}"
    echo "[wt-up] Cloning DB: ${BASE_DB} → ${DB_NAME} ..."
    # Terminate connections to template DB first
    PGPASSWORD="$DB_PASS_VAL" psql -h "$DB_HOST_VAL" -p "$DB_PORT_VAL" -U "$DB_USER_VAL" -d postgres \
        -c "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname='${BASE_DB}' AND pid <> pg_backend_pid();" \
        > /dev/null 2>&1 || true
    PGPASSWORD="$DB_PASS_VAL" createdb \
        -h "$DB_HOST_VAL" -p "$DB_PORT_VAL" -U "$DB_USER_VAL" \
        -T "$BASE_DB" "$DB_NAME"
    echo "[wt-up] DB cloned: ${DB_NAME}"
fi

# ---------------------------------------------------------------------------
# 3. Write per-worktree .env.wt
# ---------------------------------------------------------------------------

ENV_FILE="${WT_PATH}/.env.wt"
cat > "$ENV_FILE" <<EOF
# Auto-generated by wt-up.sh — gitignored, do NOT commit
WT_BRANCH=${BRANCH}
WT_SLUG=${SLUG}
WT_PORT=${PORT}
WT_DB=${DB_NAME}
WT_PATH=${WT_PATH}
WT_PROJECT=${PROJECT_NAME}

# Docker Compose overrides
CONTAINER_NAME=${CONTAINER_NAME}
OPEN_WORKFLOW_STUDIO_PATH=${WT_PATH}
ODOO_PORT=${PORT}
POSTGRES_DB=${DB_NAME}
PGDATABASE=${DB_NAME}
DB_HOST=${DB_HOST_VAL}
DB_PORT=${DB_PORT_VAL}
DB_USER=${DB_USER_VAL}
DB_PASSWORD=${DB_PASS_VAL}
ODOO_EXTRA_ARGS=--dev=xml -d ${DB_NAME} --log-level=info
ODOO_DEBUG=0
DEBUGPY_ENABLE=0
JWT_EXPIRE_TIME=999999
EOF
echo "[wt-up] .env.wt written: ${ENV_FILE}"

# ---------------------------------------------------------------------------
# 4. Register in .wt-registry
# ---------------------------------------------------------------------------

touch "$REGISTRY_FILE"
# Remove any stale entry for this slug, then append fresh
grep -v "^${SLUG}=" "$REGISTRY_FILE" > "${REGISTRY_FILE}.tmp" && mv "${REGISTRY_FILE}.tmp" "$REGISTRY_FILE" || true
echo "${SLUG}|${PORT}|${DB_NAME}|${WT_PATH}|${CONTAINER_NAME}" >> "$REGISTRY_FILE"

# ---------------------------------------------------------------------------
# 5. Start container
# ---------------------------------------------------------------------------

echo "[wt-up] Starting container ${CONTAINER_NAME} ..."
docker compose \
    -f "${REPO_ROOT}/docker-compose.yml" \
    --env-file "$ENV_FILE" \
    -p "$PROJECT_NAME" \
    up -d --build

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------

echo ""
echo "=== Worktree ready ==="
echo "  Branch:    ${BRANCH}"
echo "  Path:      ${WT_PATH}"
echo "  DB:        ${DB_NAME}"
echo "  Container: ${CONTAINER_NAME}"
echo "  URL:       http://localhost:${PORT}/odoo"
echo ""
echo "Agent: cd into ${WT_PATH} and start working."
echo "Check logs: docker compose -f ${REPO_ROOT}/docker-compose.yml -p ${PROJECT_NAME} logs -f"
echo "Smoke test: ${SCRIPTS_DIR}/wt-smoke.sh ${PORT}"
echo ""
